### ISSUE TITLE
Error when reading data

### ISSUE THREAD

**Issue by jaidayal** [sparticlesteve/cosmoflow-benchmark#23]
I am trying to run cosmoflow, but get the following error:

Traceback (most recent call last):
  File "./train.py", line 308, in <module>
    main()
  File "./train.py", line 211, in main
    datasets = get_datasets(dist=dist, **data_config)
  File "/nfshome/jdayal/cosmoflow/cosmoflow-benchmark/data/__init__.py", line 11, in get_datasets
    return get_datasets(**data_args)
  File "/nfshome/jdayal/cosmoflow/cosmoflow-benchmark/data/cosmo.py", line 157, in get_datasets
    train_dataset, n_train_steps = construct_dataset(
  File "/nfshome/jdayal/cosmoflow/cosmoflow-benchmark/data/cosmo.py", line 73, in construct_dataset
    assert (0 <= n_files) and (n_files <= len(filenames)), (
AssertionError: Requested 262144 files, 0 available

I ran it like: python ./train.py --data-dir=../cosmoUniverse_2019_05_4parE_tf_small/

I should also note, that I did make a few small code changes related to us using tf 2.4. I had to change some of the configproto and set_session calls to use v1.compat. Is this okay, or do I need to install a tensorflow 1.xx library instead?

**Comment by jaidayal** [comment]
Not a real issue. Just had to make the yaml file's metadata match the small training data.
