### ISSUE TITLE
Problem continuing from checkpoint with AMP+Horovod

### ISSUE THREAD

**Issue by sparticlesteve** [sparticlesteve/cosmoflow-benchmark#30]
I'm getting this when trying to resume some large batch size models with AMP enabled:

```
 0: Traceback (most recent call last):
 0:   File "train.py", line 388, in <module>
 0:     main()
 0:   File "train.py", line 288, in main
 0:     distributed=args.distributed)
 0:   File "/global/u2/s/sfarrell/WorkAreas/benchmarks/cosmoflow-benchmark/utils/checkpoints.py", line 74, in reload_last_checkpoint
 0:     model = load_hvd_model(checkpoint)
 0:   File "/global/u2/s/sfarrell/WorkAreas/benchmarks/cosmoflow-benchmark/utils/checkpoints.py", line 61, in load_hvd_model
 0:     return tf.keras.models.load_model(checkpoint, custom_objects=horovod_objects)
 0:   File "/usr/common/software/tensorflow/gpu-tensorflow/2.2.0-py37/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.p
y", line 184, in load_model
 0:     return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
 0:   File "/usr/common/software/tensorflow/gpu-tensorflow/2.2.0-py37/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_f
ormat.py", line 194, in load_model_from_hdf5
 0:     training_config, custom_objects))
 0:   File "/usr/common/software/tensorflow/gpu
 0: -tensorflow/2.2.0-py37/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 209, in compile_args_from_training_config
 0:     optimizer = optimizers.deserialize(optimizer_config)
 0:   File "/usr/common/software/tensorflow/gpu-tensorflow/2.2.0-py37/lib/python3.7/site-packages/tensorflow/python/keras/optimizers.py", line 869, in deserialize
 0:     printable_module_name='optimizer')
 0:   File "/usr/common/software/tensorflow/gpu-tensorflow/2.2.0-py37/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 382, in deserialize_keras_object
 0:     return cls(**cls_config)
 0:   File "/global/u2/s/sfarrell/WorkAreas/benchmarks/cosmoflow-benchmark/utils/checkpoints.py", line 54, in <lambda>
 0:     return lambda **kwargs: hvd.DistributedOptimizer(cls(**kwargs))
 0:   File "/usr/common/software/tensorflow/gpu-tensorflow/2.2.0-py37/lib/python3.7/site-packages/tensorflow/python/keras/mixed_precision/experimental/loss_scale_optimizer.py", line 125, in __init__
 0:     'got: %s' % optimizer)
 0: ValueError: "optimizer" must be an instance of OptimizerV2, but got: {'class_name': 'SGD', 'config': {'name': 'SGD', 'learning_rate': 0.01600000075995922, 'decay': 0.0, 'momentum': 0.8999999761581421, 'nesterov': False}}
```

**Comment by sparticlesteve** [comment]
While https://github.com/sparticlesteve/cosmoflow-benchmark/pull/31 does seem to fix this exception, I tried resuming my training jobs and something definitely went wrong. Quality was suddenly worse, so presumably something was not properly restored via checkpoint.

I'll need to do some further tests.

**Comment by sparticlesteve** [comment]
Turns out that reverting to build-in load_model function re-introduced the horovod resume issue from https://github.com/horovod/horovod/issues/1920.

Updating to TF 2.4.1 (and newer horovod) seems to fix it.
